out_root:
out:

dataset:
  data_root:
  name: human_v2
  bs: 6  # batchsize
  image_size: 128
  bg_color: -1

generator_params:
  use_triplane: False
  ray_batchsize: 4096
  nerf_params:
    hidden_size: 32  # hidden size of NeRF
    Nc: 48  # number of points for coarse sampling
    Nf: 64  # number of points for fine sampling
    no_world_pose: False
    no_ray_direction: True
    density_activation: MyReLU
    origin_location: center_fixed  # origin of local coordinate, root or center
    coordinate_scale: 3
    render_bs: 16384
    # mlp model
    model_type: "narf"

    # tri-plane model
    multiply_density_with_triplane_wieght: False
    clamp_mask: False
    constant_triplane: False
    constant_trimask: False  # only tri-plane mask is constant
    selector_mlp: False
    deformation_field: False
    no_selector: False
    # if deformation_field
    time_conditional: True
    pose_conditional: False
    constant_trimask_lr_mul: 1

