out_root: data
out: DSO/ZJU/386_denarf

sample_path: data/ZJU/386

dataset:
  bs: 16  # batchsize
  image_size: 512


generator_params:
  use_triplane: True
  nerf_params:
    deformation_field: True
    pose_conditional: True
    render_bs: 16384
