# paths
out_root: path_to_your_output_root  # <- need change
out: output_directory  # <- need change

dataset:
  data_root:
  name: hand2
  bs: 6  # batchsize
  image_size: 128
  train:
    random_background: True
    data_root: path_to_your_dataset_root  # <- need change
    n_frames: number_of_frames
    n_camera: 4
  val:
    train:
      data_root: path_to_your_dataset_root  # <- need change
      n_frames: number_of_frames
      n_camera: 4
    novel_view:
      data_root: path_to_your_dataset_root  # <- need change
      n_frames: number_of_frames
      n_camera: 17
    novel_pose:
      data_root: path_to_your_dataset_root  # <- need change
      n_frames: number_of_frames
      n_camera: 17



generator_params:
  use_triplane: False
  ray_batchsize: 4096
  nerf_params:
    hidden_size: 32  # hidden size of NeRF
    Nc: 48  # number of points for coarse sampling
    Nf: 48  # number of points for fine sampling
    no_world_pose: False
    no_ray_direction: False
    density_activation: MyReLU
    origin_location: center  # origin of local coordinate, root or center
    coordinate_scale: 3
    render_bs: 16384
    # mlp model
    model_type: "narf"

    # tri-plane model
    multiply_density_with_triplane_wieght: False
    clamp_mask: False
    constant_triplane: False
    constant_trimask: False  # only tri-plane mask is constant
    selector_mlp: False
    deformation_field: False
    # if deformation_field
    time_conditional: True
    pose_conditional: False
    constant_trimask_lr_mul: 1
loss:
  color_coef: 1
  mask_coef: 1
  nerf_loss_type: mse
  surface_reg_coef: 0

# hyper parameters
num_iter: 100000
lr: 0.001
scheduler_gamma: 0.99995
val_interval: 500 # validation interval
print_interval: 10
tensorboard_interval: 100
save_interval: 200

# snapshots
resume: # path to snapshot

# For DDP
master_addr: 'localhost'
master_port: '12357'
backend: 'nccl'
