# NARF + Neural Rendering + GAN
# paths
out_root: /data/unagi0/noguchi/D1/NARF_GAN
out: THUman/GAN/20220216_wild_const_trimask_pretrained.yml

dataset:
  name: human_tight
  bs: 10  # batchsize
  image_size: 128
  train:
    data_root: /data/unagi0/noguchi/dataset/COCO/crop128  # <- need change
    pose_prior_root: /data/unagi0/noguchi/dataset/mosh/CMU

generator_params:
  z_dim: 256
  background_ratio: 0.3
  use_triplane: True
  crop_background: True
  pretrained_background: True
  nerf_params:
    hidden_size: 256  # hidden size of NeRF
    Nc: 48  # number of points for coarse sampling
    Nf: 64  # number of points for fine sampling
    density_activation: MyReLU
    # concat model
    origin_location: center  # origin of local coordinate, root or center
    coordinate_scale: 3
    # tri-plane model
    multiply_density_with_triplane_wieght: True
    clamp_mask: False
    constant_trimask: True

discriminator_params:
  minibatch_std: False

loss:
  adv_loss_type: ce
  bone_guided_coef: 10
  nerf_coef: 1
  color_coef: 1
  mask_coef: 3
  push_to_background_coef: 5
  nerf_loss_type: mse
  ignore_boundary: False
  suppress_small: False
  r1_loss_coef: 10
  tri_plane_reg_coef: 0.001
  tri_plane_mask_reg_coef: 0.0
consistency_regularization: False
replace: True
mix_nerf_and_cnn: True
start_replace: 4000
start_gen_training: 0
consistency_regularization_coef: 0.0
nerf_only: True

num_iter: 800000

# snapshots
#resume: /data/unagi0/noguchi/D1/NARF_GAN/result/THUman/GAN/20220204_wild_triplane/snapshot_200000.pth