# NARF + Neural Rendering + GAN
# paths
out_root: data
out: GAN/AIST/enarfgan

sample_path: data/aist++

dataset:
  name: human_v2
  bs: 12  # batchsize
  image_size: 128

generator_params:
  z_dim: 256
  use_triplane: True
  crop_background: True
  nerf_params:
    hidden_size: 256  # hidden size of NeRF
    Nc: 48  # number of points for coarse sampling
    Nf: 64  # number of points for fine sampling
    origin_location: center_fixed  # origin of local coordinate, root or center
    coordinate_scale: 3
