# NARF + Neural Rendering + GAN
# paths
out_root: /data/unagi0/noguchi/D1/NARF_GAN
out: THUman/GAN/20211227_CMUPrior

dataset:
  name: human
  bs: 6  # batchsize
  image_size: 128
  train:
    random_background: False
    data_root: /data/unagi0/noguchi/dataset/THUman/all_person  # <- need change
    pose_prior_root: /data/unagi0/noguchi/dataset/mosh/CMU
    background_path: /data/unagi0/noguchi/dataset/lsun/bedroom128.npy

generator_params:
  no_nerf_bn: True
  z_dim: 256
  patch_size: 32
  use_nerf: Ture
  z_bg_dim: 0
  bg_activation: l2 # tanh or None
  nerf_params:
    final_activation: l2
    hidden_size: 256  # hidden size of NeRF
    out_dim: 256  # output channel of NeRF
    Nc: 48  # number of points for coarse sampling
    Nf: 48  # number of points for fine sampling
    no_world_pose: True
    no_ray_direction: True
    concat: True
    density_activation: MyReLU
    density_scale: 1
    # concat model
    mask_input: True
    hard_mask: False
    use_scale_factor: True

discriminator_params:
  minibatch_std: False

loss:
  adv_loss_type: ce
  bone_guided_coef: 10
  nerf_coef: 1
  color_coef: 1
  mask_coef: 3
  push_to_background_coef: 5
  nerf_loss_type: mse
  ignore_boundary: False
  suppress_small: False
  r1_loss_coef: 10

consistency_regularization: False
replace: True
mix_nerf_and_cnn: True
start_replace: 4000
start_gen_training: 0
consistency_regularization_coef: 0.0
nerf_only: True

num_iter: 200000

# snapshots
#resume: /data/unagi0/noguchi/D1/NARF_GAN/result/THUman/GAN/20211212_NoPoseAndRayDirection/snapshot_latest.pth