# NARF + Neural Rendering + GAN
# paths
out_root: data
out: DSO/ZJU/386_enarf

sample_path: data/ZJU_DSO/386

dataset:
  bs: 16  # batchsize
  image_size: 512

generator_params:
  use_triplane: True
  nerf_params:
    constant_triplane: True