out_root: data
out: DSO/NeuralActor/marc_enarf

dataset:
  name: human_v2
  bs: 16  # batchsize
  image_size: 1024
  bg_color: 1
  train:
    data_root: data/NeuralActor/marc/train_cache_38194  # <- need change
    n_frames: 38194
    n_camera: 11
  val:
    novel_pose:
      data_root: data/NeuralActor/marc/test_debug_cache_23062  # <- need change
      n_frames: 23062
      n_camera: 11

generator_params:
  use_triplane: True
  nerf_params:
    hidden_size: 256  # hidden size of NeRF
    Nc: 48  # number of points for coarse sampling
    Nf: 64  # number of points for fine sampling
    no_ray_direction: True
    # concat model
    origin_location: center_fixed  # origin of local coordinate, root or center
    coordinate_scale: 3
    constant_triplane: True

loss:
  color_coef: 1
  mask_coef: 1
  nerf_loss_type: mae

# hyper parameters
num_iter: 100000
lr: 0.001
scheduler_gamma: 0.99997
val_interval: 500 # validation interval
print_interval: 10
tensorboard_interval: 100
save_interval: 500

# snapshots
#resume: