# NARF + Neural Rendering + GAN
# paths
out_root: /data/unagi0/noguchi/D1/NARF_GAN
out: THUman/SSO/20220215_zju313_triplane

dataset:
  name: human_v2
  bs: 16  # batchsize
  image_size: 512
  train:
    data_root: /data/unagi0/noguchi/dataset/animatable_nerf_zju/CoreView_313/train_cache_60  # <- need change
    n_frames: 60
  val:
    train:
      data_root: /data/unagi0/noguchi/dataset/animatable_nerf_zju/CoreView_313/train_cache_60  # <- need change
      n_frames: 60
    novel_view:
      data_root: /data/unagi0/noguchi/dataset/animatable_nerf_zju/CoreView_313/test_novel_view_cache_60  # <- need change
      n_frames: 60
    novel_pose:
      data_root: /data/unagi0/noguchi/dataset/animatable_nerf_zju/CoreView_313/test_novel_pose_cache_1000  # <- need change
      n_frames: 1000


generator_params:
  use_triplane: True
  ray_batchsize: 4096
  nerf_params:
    hidden_size: 256  # hidden size of NeRF
    Nc: 48  # number of points for coarse sampling
    Nf: 64  # number of points for fine sampling
    density_activation: MyReLU
    # concat model
    origin_location: center  # origin of local coordinate, root or center
    coordinate_scale: 3

loss:
  color_coef: 3
  mask_coef: 1
  nerf_loss_type: mse

# hyper parameters
num_iter: 100000
lr: 0.001
scheduler_gamma: 0.99995
val_interval: 500 # validation interval
print_interval: 10
tensorboard_interval: 100
save_interval: 500

# snapshots
#resume: /data/unagi0/noguchi/D1/NARF_GAN/result/THUman/SSO/20220215_zju_triplane/snapshot_latest.pth